name: Build
permissions:
  checks: write
  pull-requests: write
on:
  push:
    branches:
      - master
      - 3.x
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'
      - name: Build
        run: ./gradlew build
      - uses: codecov/codecov-action@v5
        with:
          verbose: true
